### ISSUE TITLE
Fatal Error: Failure to Recognize Content from README File Correctly

### ISSUE THREAD

**Issue by Glitch-art** [seattlerb/hoe#116]
When executing the command `rake gem:spec --trace` in my local environment, I encounter the following error related to the execution of the `intuit_values` method in `hoe.rb` at line 683

```
PS C:\forks\ruby-opencv> rake gem:spec --trace
rake aborted!
NoMethodError: undefined method `join' for nil:NilClass

                 [kp, v.join.strip]
                       ^^^^^
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/hoe-4.2.0/lib/hoe.rb:686:in `block in intuit_values'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/hoe-4.2.0/lib/hoe.rb:678:in `each_slice'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/hoe-4.2.0/lib/hoe.rb:678:in `each'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/hoe-4.2.0/lib/hoe.rb:678:in `to_h'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/hoe-4.2.0/lib/hoe.rb:678:in `intuit_values'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/hoe-4.2.0/lib/hoe.rb:828:in `post_initialize'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/hoe-4.2.0/lib/hoe.rb:406:in `spec'
```

In my opinion, this error can happen, but it should not be fatal and stop the entire process.

## Environment
Operating System: Windows 10
Ruby Version: ruby-3.2.3
Hoe Version: hoe-4.2.0

**Comment by zenspider** [comment]
```ruby
    readme = input
               .lines
               .chunk { |l| l[/^(?:=+|#+)/] || "" }
               .map(&:last)
               .each_slice(2)
               .to_h { |k, v|
                 kp = k.map { |s|
                   s.strip.chomp(":").sub(/(?:=+|#+)\s*/, '').downcase
                 }.join("\n")

                 [kp, v.join.strip]
               }
```

guessing it is an odd number of elements for that `each_slice` to come up w/ `v` being `nil` ?

**Comment by zenspider** [comment]
Just pushed a change that'll raise telling you what section is broken

**Comment by zenspider** [comment]
No response. Closing.
