### ISSUE TITLE
app_root?

### ISSUE THREAD

**Issue by utilum** [seattlerb/hoe#82]
I don't understand: 

```
[oz@oznix240 ~]$ sow something
erb: .autotest.erb
erb: .gitignore
erb: .rubocop.yml
erb: History.txt.erb
erb: Manifest.txt.erb
erb: README.txt.erb
erb: Rakefile.erb
erb: bin/file_name.erb
erb: lib/file_name.rb.erb
erb: test/test_file_name.rb.erb

... done, now go fix all occurrences of 'FIX':

  something/README.txt:3:home  :: FIX (url)
  something/README.txt:4:code  :: FIX (url)
  something/README.txt:5:rdoc  :: FIX (url)
  something/README.txt:6:bugs  :: FIX (url)
  something/README.txt:11:FIX (describe your package)
  something/README.txt:15:* FIX (list of features or problems)
  something/README.txt:19:  FIX (code sample of usage)
  something/README.txt:23:* FIX (list of requirements)
  something/README.txt:27:* FIX (sudo gem install, anything else)
  something/README.txt:42:Copyright (c) 2017 FIX
  
[oz@oznix240 ~]$ cd something/
[oz@oznix240 something]$ rake newb
rm -rf doc
/home/oz/.rbenv/versions/2.4.1/bin/ruby /home/oz/.rbenv/versions/2.4.1/bin/rdoc --title something-1.0.0 Documentation -o doc --main README.txt lib History.txt Manifest.txt README.txt
Parsing sources...
100% [ 4/ 4]  lib/something.rb

Generating Darkfish format into /home/oz/something/doc...

  Files:      4

  Classes:    1 (1 undocumented)
  Modules:    0 (0 undocumented)
  Constants:  1 (1 undocumented)
  Attributes: 0 (0 undocumented)
  Methods:    0 (0 undocumented)

  Total:      2 (2 undocumented)
    0.00% documented

  Elapsed: 0.1s

/home/oz/.rbenv/versions/2.4.1/bin/ruby -w -Ilib:bin:test:. -e 'require "rubygems"; require "minitest/autorun"; require "test/test_something.rb"' -- 
Run options: --seed 46787

# Running:

F

Failure:
TestSomething#test_sanity [/home/oz/something/test/test_something.rb:7]:
write tests or I will kneecap you


/home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/test_unit/reporter.rb:75:in `app_root': undefined method `root' for Rails:Module (NoMethodError)
	from /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/test_unit/reporter.rb:53:in `relative_path_for'
	from /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/test_unit/reporter.rb:71:in `format_rerun_snippet'
	from /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/test_unit/reporter.rb:23:in `record'
	from /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:682:in `block in record'
	from /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:681:in `each'
	from /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:681:in `record'
	from /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:324:in `run_one_method'
	from /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:311:in `block (2 levels) in run'
	from /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:310:in `each'
	from /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:310:in `block in run'
	from /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:350:in `on_signal'
	from /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:337:in `with_info_handler'
	from /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:309:in `run'
	from /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:159:in `block in __run'
	from /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:159:in `map'
	from /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:159:in `__run'
	from /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:136:in `run'
	from /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:63:in `block in autorun'
rake aborted!
Command failed with status (1): [/home/oz/.rbenv/versions/2.4.1/bin/ruby -w...]

Tasks: TOP => newb => default => test
(See full trace by running task with --trace)
```

**Comment by zenspider** [comment]
I don't understand either and I don't have enough information to go on...

The problem lies on this boundary:

```
	from /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/test_unit/reporter.rb:23:in `record'
	from /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:682:in `block in record'
```

but the source of the problem could be in `Rakefile.erb` `test/test_file_name.rb.erb` or in some gem messing with the reporters...

You might try upgrading to rails 5.1.3 as it has some changes specifically for minitest.

**Comment by utilum** [comment]
Thank you, updating Rails resolved this.
But it looked to me like a railties dependence had crept into the blank project uninvited. That's not intended, is it?

**Comment by utilum** [comment]
Oh...

```grep -ri rail /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hoe-3.16.1/
Binary file /home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hoe-3.16.1/Hoe.pdf matches
/home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hoe-3.16.1/lib/hoe/rake.rb:  #   require 'tasks/rails'
/home/oz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hoe-3.16.1/lib/hoe/rake.rb:  #   Rake.undo("test") # rolls out rails' test task
```

**Comment by zenspider** [comment]
No, hoe knows nothing of rails. You might want to check your `~/.hoe_template` directories.

what you grepped... those are comments...

**Comment by zenspider** [comment]
anything?

**Comment by utilum** [comment]
Sorry for the delay, it was fixed by updating rails. And the root cause is an over-inclusive path in my shell settings. Hoe is clean :)
