### ISSUE TITLE
packaging error

### ISSUE THREAD

**Issue by oberon2007** [seattlerb/hoe#83]
Trying to update the AUR package to **v3.16.2** packageing fails with:

```
==> Starting package()...
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- ubygems (LoadError)
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Successfully installed hoe-3.16.2
Parsing documentation for hoe-3.16.2
Installing ri documentation for hoe-3.16.2
Done installing documentation for hoe after 0 seconds
1 gem installed
rm: cannot remove '/logdest/logpipe.rnuMP5tf': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
```

**Comment by oberon2007** [comment]
`ubygems` sic! really? Is this maybe just a typo in the test?

**Comment by oberon2007** [comment]
I was able to fix this in the PKGBUILD, thanks :)
